### ISSUE TITLE
Sample data Not present

### ISSUE THREAD

**Issue by abraryousuf** [MAfarrag/HAPI#28]
Hi 

Thanks for sharing the repo. I tried to run the project , but there are some files missing in input data. Can you upload the some sample so that i can run end to end 

Thanks

**Comment by MAfarrag** [comment]
the Example folder is updated with a notebook containing a link to a google drive where you can download the data for all the examples([Prepare inputs](https://github.com/MAfarrag/HAPI/blob/master/Examples/01prepare_inputdata.ipynb),  [Run Hapi](https://github.com/MAfarrag/HAPI/blob/master/Examples/03Jiboa.ipynb))
