### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by juancotrino** [MAfarrag/Hapi#31]
Just a couple of bugs that need to be fixed:

1. In the module `calibration.py` line `204` it is necessary to change the function name `Dist_model` to `HapiModel` since the name of the function has been changed in the new version of Hapi 0.3.0.

2. In the module `distparameters.py` the arguments of the function `par3dLumped` should be `(par_g,raster,no_parameters,no_lumped_par=None,lumped_par_pos=None,kub=1,klb=0.5,Maskingum = True):`, although the variables `no_lumped_par` and `lumped_par_pos` are not needed (that's why it would be better to set them by default as `None`), but because the function `SaveParameters` states them in the line `707`. So it's either change this last line mentioned or state them as `None` by default in the `par3dLumped`.

3. It would be good to add this line of code: `if ".DS_Store" in files: files.remove(".DS_Store")` under line `1947` on `raster.py` module to ensure MacOS compatibility. (That could be done where needed as well)

**Comment by corzogac** [comment]
Thank you Juan Manuel

Can you use Github to provide the updated version?
and
@mostafa ahmed <moah.farag@gmail.com>  can you accept the (check) the
update version proposed by Juan Manual


Regarsd

Dr Ir. Gerald Augusto Corzo Perez

Associate professor and Senior Researcher
Chair Group of Hydroinformatics
Department of Integrated Water Systems and Governance

*IHE Delft Institute for Water Education*

Westvest 7, 2611 AX Delft
PO Box 3015, 2601 DA Delft
The Netherlands

*www.un-ihe.org <http://www.un-ihe.org/>*
https://www.mdpi.com/journal/jmse/special_issues/spatiotemporal_data_analysis
The Foundation is an independent entity not affiliated with UNESCO.
UNESCO is not responsible for the Foundation's actions and omissions.

**Comment by juancotrino** [comment]
Sure, already pushed the changes.

Thanks
