### ISSUE TITLE
Sallite Data Does not Download 

### ISSUE THREAD

**Issue by julian1410** [MAfarrag/Hapi#71]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**

**Expected behaviour**

**Screenshots**

![image](https://user-images.githubusercontent.com/64171210/158845185-12059b2e-7bd8-44f9-9382-79790237856c.png)

  File ~\OneDrive - ESCUELA COLOMBIANA DE INGENIERIA JULIO GARAVITO (1)\IHE\TESIS\HAPI\METEO_DATA\Get_Data.py:36 in <module>
    Coello.ECMWF(Waitbar=1)

  File ~\Anaconda3\envs\HidroMod\lib\site-packages\Hapi\rs\remotesensing.py:133 in ECMWF
    self.DownloadData(var, Waitbar)  # CaseParameters=[SumMean, Min, Max]

  File ~\Anaconda3\envs\HidroMod\lib\site-packages\Hapi\rs\remotesensing.py:286 in DownloadData
    Raster.CreateRaster(Path=name_out, data=Data_end, geo=Geo_out, EPSG="WGS84")

TypeError: CreateRaster() got an unexpected keyword argument 'data'

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MAfarrag** [comment]
Hey @julian1410 I was able to reproduce the error and now it works, however the parameter `Waitbar` is change now to be bool type so please change it in your code from 1 to True
